title: cripto.wiki
description: descifrando el mundo de Bitcoin, privacidad & ciberseguridad
url: https://cripto.wiki
language: es
baseurl: ''

social:
  twitter: criptowiki
  instagram: cripto.wiki
  mastodon: criptowiki

collections_dir: collections
collections:
  articles:
    output: true
  calendar:
    output: true
  tutorials:
    output: true
  tools-bitcoin:
    output: true
  tools-cybersecurity:
    output: true
  myths:
    output: true
  dictionary:
    output: true
  wallets:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'calendar'
    values:
      layout: 'calendar'
  - scope:
      path: ''
      type: 'tutorials'
    values:
      layout: 'tutorial'
  - scope:
      path: ''
      type: 'tools-cybersecurity'
    values:
      layout: 'tool'
  - scope:
      path: ''
      type: 'myths'
    values:
      layout: 'myth'
  - scope:
      path: ''
      type: 'dictionary'
    values:
      layout: 'dictionary-definition'
  - scope:
      path: ''
      type: 'wallets'
    values:
      layout: 'wallet'

sass:
  style: compressed

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false

include: [CNAME]