title: cripto.wiki
description: descifrando el mundo de Bitcoin, privacidad & ciberseguridad
url: https://cripto.wiki
language: es
baseurl: ''

social:
  twitter: criptowiki
  instagram: cripto.wiki
  reddit: criptowiki
  mastodon: criptowiki

collections_dir: collections
collections:
  history:
    output: true
  tutorials:
    output: true
  tools-bitcoin:
    output: true
  tools-cybersecurity:
    output: true
  myths:
    output: true
  dictionary:
    output: true
  wallets:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'history'
    values:
      layout: 'history'
  - scope:
      path: ''
      type: 'tutorials'
    values:
      layout: 'tutorial'
  - scope:
      path: ''
      type: 'tools-cybersecurity'
    values:
      layout: 'tool'
  - scope:
      path: ''
      type: 'myths'
    values:
      layout: 'myth'
  - scope:
      path: ''
      type: 'dictionary'
    values:
      layout: 'dictionary-definition'
  - scope:
      path: ''
      type: 'wallets'
    values:
      layout: 'wallet'

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false

include: [CNAME]
exclude: [LICENSE.txt, README.md, cripto.wiki.gemspec]