title: cripto.wiki
description: descifrando el mundo de Bitcoin, privacidad & ciberseguridad
url: https://cripto.wiki
language: es
baseurl: ''

social:
  twitter: criptowiki
  instagram: cripto.wiki
  reddit: criptowiki
  mastodon: criptowiki

collections_dir: collections

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: '_posts/bitcoin/'
    values:
      layout: 'article'
      category: 'bitcoin'
  - scope:
      path: '_posts/history/'
    values:
      layout: 'history'
      category: 'history'
  - scope:
      path: '_posts/tools-cybersecurity/'
    values:
      layout: 'tool'
      category: 'tools-cybersecurity'
  - scope:
      path: '_posts/myths/'
    values:
      layout: 'myth'
      category: 'myths'
  - scope:
      path: '_posts/dictionary/'
    values:
      layout: 'dictionary-definition'
      category: 'dictionary'
  - scope:
      path: '_posts/wallets/'
    values:
      layout: 'wallet'
      category: 'wallets'

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  ignore:
    envs: [development] # bundle exec jekyll serve JEKYLL_ENV=development

include: [CNAME]
exclude: [LICENSE.txt, README.md, cripto.wiki.gemspec]