title: criptowiki
description: descifrando el mundo de Bitcoin, privacidad & ciberseguridad
url: https://criptowiki.com
language: es
baseurl: ''

social:
  twitter: criptowiki
  instagram: cripto.wiki
  reddit: criptowiki
  mastodon: criptowiki

collections_dir: collections

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: '_posts/bitcoin/'
    values:
      layout: 'article'
      category: 'bitcoin'
  - scope:
      path: '_posts/history/'
    values:
      layout: 'history'
      category: 'history'
  - scope:
      path: '_posts/cybersecurity/'
    values:
      layout: 'post-two-column'
      category: 'cybersecurity'
  - scope:
      path: '_posts/myths/'
    values:
      layout: 'myth'
      category: 'myths'
  - scope:
      path: '_posts/dictionary/'
    values:
      layout: 'post-two-column'
      category: 'dictionary'
  - scope:
      path: '_posts/wallets/'
    values:
      layout: 'wallet'
      category: 'wallets'

sass:
  style: compressed

pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate-v2

feed:
  path: /feed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  ignore:
    envs: [development] # bundle exec jekyll serve JEKYLL_ENV=development

include: [CNAME]
exclude: [LICENSE.txt, README.md, criptowiki.gemspec]