name: jekyll

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: helaili/jekyll-action@2.2.0
      with:
        token: ${{ secrets.CW_GH_PAGES_TOKEN }}
        target_branch: 'test-gh-pages'